name: WWW.APP
version: 0.1.10
description: Website.
author: Louise van der Lith
repository: https://github.com/louisevanderlith/www
environment:
  sdk: '>=2.0.0 < 3.0.0'
dev_dependencies:
  build_runner: '>=1.0.0 <2.0.0'
  build_web_compilers: '>=2.6.1 <3.0.0'
dependencies:
  mango_ui: '^1.0.3'
  dart_toast: '^0.3.0'
  mango_comms: '^1.0.2'
  mango_comment: '^1.0.0'